### ISSUE TITLE
Run examples/bert.py, it report expected mlir::RankedTensorType, but got: 'i32'

### ISSUE THREAD

**Issue by zhping5678** [iree-org/iree-torch#76]
When I run the demo in 'examples/bert.py' and invoke  `iree_torch.compile_to_vmfb(linalg_on_tensors_mlir, args.iree_backend)`,  it reports **expected mlir::RankedTensorType, but got: 'i32'**

Complete information is below.

```
Compiling with IREE
Traceback (most recent call last):
  File "../iree-torch/examples/bert.py", line 115, in <module>
    main()
  File "../iree-torch/examples/bert.py", line 102, in main
    iree_vmfb = iree_torch.compile_to_vmfb(linalg_on_tensors_mlir, args.iree_backend)
  File "~/anaconda3/envs/python38/lib/python3.8/site-packages/iree_torch/__init__.py", line 103, in compile_to_vmfb
    return ireec.compile_str(bytecode,
  File "~/anaconda3/envs/python38/lib/python3.8/site-packages/iree/compiler/tools/core.py", line 277, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "~/anaconda3/envs/python38/lib/python3.8/site-packages/iree/compiler/tools/binaries.py", line 196, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
<stdin>:0:0: error: expected mlir::RankedTensorType, but got: 'i32'
<stdin>:0:0: note: in bytecode version 0 produced by: MLIR16.0.0git

**Comment by jpienaar** [comment]
@dellis23 do you know what might cause this?

**Comment by dellis23** [comment]
In general, these sorts of issues tend to be caused by version skew and incompatibilities between torch-mlir and IREE.  We're discussing solutions internally.  I just tested out the [notebook version](https://colab.research.google.com/github/iree-org/iree-torch/blob/main/examples/bert.ipynb) of that example, and things seem to be working right now.  Did this end up resolving for you @zhping5678?  Does the linked colab work for you?
